# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrs.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sha256_encryptor_0_0/design_1_sha256_encryptor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sha256_encryptor_0_0 || ORIG_REF_NAME==design_1_sha256_encryptor_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_mcs_0_0/design_1_microblaze_mcs_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_mcs_0_0 || ORIG_REF_NAME==design_1_microblaze_mcs_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_if_cntlr_0_0/design_1_lmb_bram_if_cntlr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_if_cntlr_0_0 || ORIG_REF_NAME==design_1_lmb_bram_if_cntlr_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_3/design_1_clk_wiz_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_3 || ORIG_REF_NAME==design_1_clk_wiz_3} -quiet] -quiet

# XDC: /home/sasarmandarius/Desktop/LabCA/project_bonus/project_bonus.gen/sources_1/bd/design_1/design_1_ooc.xdc
